# CI/CD configuration file to test install and run alignment, SRS and trim FASTA on tests data.

stages:          # List of stages for jobs, and their order of execution
  - testInstall
  - hiSATalign
  - splitReadSearch
  - trimFastaFromTXT

testInstall-job:       # This job first runs tests on intronSeeker install.
  stage: testInstall
  script:
    - echo "Tests on intronSeeker installation..."
    - curl https://forgemia.inra.fr/emilien.lasguignes/intronSeeker.git
    - module load system/Miniconda3-4.7.10;
    - cd intronSeeker/
    - ./setup.sh
    - source activate ISeeker_environment
    - intronSeeker checkInstall
    - echo "End install and check installation..."


hiSATalign-job:   
  stage: hiSATalign    # It only starts when the job in the test intallation stage completes successfully.
  script:
    - echo "Reads alignment on reference contigs with Hisat"
    - intronSeeker hisat2Alignment -r data/Reduced_real_dataset/Test_set_Cele_contig-assembly.fasta -1 data/Reduced_real_dataset/Test_set_Cele_reads-1.fastq.gz -2 data/Reduced_real_dataset/Test_set_Cele_reads-2.fastq.gz -o data/Reduced_real_dataset/Cele_library-contigs_HISAT2Alignment
  artifacts:
    paths:
      - tests/


splitReadSearch-job:   
  stage: splitReadSearch   
  script:
    - echo "Splicing event search"
    - intronSeeker splitReadSearch -a data/Reduced_real_dataset/Cele_library-contigs_HISAT2Alignment/hisat2.sort.bam -r data/Reduced_real_dataset/Test_set_Cele_contig-assembly.fasta -o data/Reduced_real_dataset/Test_Cele_splicing_event_HISAT2


trimFastaFromTXT-job:      
  stage: trimFastaFromTXT
  script:
    - echo "List features by FASTA trimming"
    - intronSeeker trimFastaFromTXT -r data/Reduced_real_dataset/Test_set_Cele_contig-assembly.fasta -c data/Reduced_real_dataset/Test_Cele_splicing_event_HISAT2/srs_candidates.txt -o data/Reduced_real_dataset/Test_Cele_trimFASTA

    
