# CI/CD configuration file to test install and run alignment, SRS and trim FASTA on tests data.
stages:  # List of stages for jobs, and their order of execution
  - testInstall
  - align
  - splitReadSearch
  - trimFastaFromTXT


testInstall-job:       # This job first runs tests on intronSeeker install.
  stage: testInstall
  tags: ["stable"]
  image: docker:20.10.20
  services:
    - docker:20.10.20-dind
  variables:
    DOCKER_TLS_CERTDIR: "/certs"
    DOCKER_DRIVER: overlay2
    DOCKER_BUILDKIT: 1
  before_script:
    - docker info
    - echo $CI_JOB_TOKEN | docker login -u $CI_REGISTRY_USER --password-stdin $CI_REGISTRY
  script:
    - docker build 
        --tag $CI_REGISTRY_IMAGE:intronSeeker
        --build-arg BUILDKIT_INLINE_CACHE=1
        - < Dockerfile
  after_script:
    - docker push $CI_REGISTRY_IMAGE:intronSeeker


hiSATalign-job:   
  stage: align    # It only starts when the job in the test intallation stage completes successfully.
  image: $CI_REGISTRY_IMAGE:intronSeeker
  script:
    - echo "Reads alignment on reference contigs with Hisat"
    - intronSeeker hisat2Alignment -r data/Reduced_real_dataset/Test_set_Cele_contig-assembly.fasta -1 data/Reduced_real_dataset/Test_set_Cele_reads-1.fastq.gz -2 data/Reduced_real_dataset/Test_set_Cele_reads-2.fastq.gz -o data/Reduced_real_dataset/Cele_library-contigs_HISAT2Alignment
  artifacts:
    paths:
      - tests/


STARalign-job:   
  stage: align    # It only starts when the job in the test intallation stage completes successfully.
  image: $CI_REGISTRY_IMAGE:intronSeeker
  script:
    - echo "Reads alignment on reference contigs with STAR"
    - intronSeeker hisat2Alignment -r data/Reduced_real_dataset/Test_set_Cele_contig-assembly.fasta -1 data/Reduced_real_dataset/Test_set_Cele_reads-1.fastq.gz -2 data/Reduced_real_dataset/Test_set_Cele_reads-2.fastq.gz -o data/Reduced_real_dataset/Cele_library-contigs_HISAT2Alignment
  artifacts:
    paths:
      - tests/


splitReadSearch-job:   
  stage: splitReadSearch   
  image: $CI_REGISTRY_IMAGE:intronSeeker
  script:
    - echo "Splicing event search"
    - intronSeeker splitReadSearch -a data/Reduced_real_dataset/Cele_library-contigs_HISAT2Alignment/hisat2.sort.bam -r data/Reduced_real_dataset/Test_set_Cele_contig-assembly.fasta -o data/Reduced_real_dataset/Test_Cele_splicing_event_HISAT2


trimFastaFromTXT-job:      
  stage: trimFastaFromTXT
  image: $CI_REGISTRY_IMAGE:intronSeeker
  script:
    - echo "List features by FASTA trimming"
    - intronSeeker trimFastaFromTXT -r data/Reduced_real_dataset/Test_set_Cele_contig-assembly.fasta -c data/Reduced_real_dataset/Test_Cele_splicing_event_HISAT2/srs_candidates.txt -o data/Reduced_real_dataset/Test_Cele_trimFASTA
